language: php

php:
  - 7.2
  - 7.3
  - 7.4

services:
  - mysql
addons:
  hosts:
    - blank

sudo: false

before_install:
  - mysql -e 'CREATE DATABASE awesome;'

install:
  - composer install

script:
  - pwd
  - php vendor/bin/codecept run unit -v --coverage-xml --env travis

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover tests/_output/coverage.xml
