language: php

php:
  - 7.1
  - 7.2
  - 7.3

services:
  - mysql
addons:
  hosts:
    - blank

sudo: false

before_install:
  - mysql -e 'CREATE DATABASE awesome;'

install:
  - composer install

script:
  - php vendor/bin/codecept run unit --coverage-xml --env travis

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover tests/_output/coverage.xml
